const msAppartment = Object.values(
  import.meta.glob("../assets/images/msAppartment/*.{jpeg,jpg,png,webp}", {
    eager: true,
    import: "default",
  })
);

const hydAirport = Object.values(
  import.meta.glob("../assets/images/hydAirport/*.{jpeg,jpg,png,webp}", {
    eager: true,
    import: "default",
  })
);

const hirandaini = Object.values(
  import.meta.glob("../assets/images/hirandaini/*.{jpeg,jpg,png,webp}", {
    eager: true,
    import: "default",
  })
);

const naviAirport = Object.values(
  import.meta.glob("../assets/images/naviAirport/*.{jpeg,jpg,png,webp}", {
    eager: true,
    import: "default",
  })
);
const desai = Object.values(
  import.meta.glob("../assets/images/nKDesai/*.{jpeg,jpg,png,webp}", {
    eager: true,
    import: "default",
  })
);

const PROJECTS = [
  {
    srNo: 1,
    project: "Vikas Paradise Residential Tower - 20 Floors, 120 Flats",
    area: "Mulund",
    location: "Mumbai",
    year: "2008-10",
    client: "Ashford Corporation",
    contactPerson: "Mr. Ketan Gada",
    contactNumber: "9820123434",
    amount: "₹ 2,100,000.00",
  },
  {
    srNo: 2,
    project: "IIT Pawai Hostel Bldg No 15  3 Wings - 10 Floors, 540 Rooms",
    area: "IIT Powai",
    location: "Mumbai",
    year: "2009-11",
    client: "M/S Unity Infra",
    contactPerson: "Mr. Rane",
    contactNumber: "9890464219",
    amount: "₹ 1,800,000.00",
  },
  {
    srNo: 3,
    project: "Madhuban Residential - 8 Floors, 16 Flats",
    area: "Matunga East",
    location: "Mumbai",
    year: "2009-13",
    client: "Ashford Corporation",
    contactPerson: "Mr. Ketan Gada",
    contactNumber: "9820123434",
    amount: "₹ 2,200,000.00",
  },
  {
    srNo: 4,
    project: "Hiranandani Estate Thane Bldg Name: EVA - 18 Floors, 65 Flats",
    area: "Thane",
    location: "Mumbai",
    year: "2013-15",
    client: "M/S Sew Engg",
    contactPerson: "Mr. Ashok Sabat",
    contactNumber: "9867030723",
    amount: "₹ 2,200,000.00",
  },
  {
    srNo: 5,
    project:
      "Hiranandani Estate Thane Bldg Name: Cardinal - 27 Floors, 163 Flats",
    area: "Thane",
    location: "Mumbai",
    year: "2015-17",
    client: "M/S Sew Engg",
    contactPerson: "Mr. Nandakumar Pawar",
    contactNumber: "8828092974",
    amount: "₹ 5,300,000.00",
  },
  {
    srNo: 6,
    project:
      "One Hiranandani Park Thane Bldg Name: Clifton - 27 Floors, 103 Flats",
    area: "Thane",
    location: "Mumbai",
    year: "2017-19",
    client: "M/S Sew Engg",
    contactPerson: "Mr. Nandakumar Pawar",
    contactNumber: "8828092974",
    amount: "₹ 4,100,000.00",
  },
  {
    srNo: 7,
    project: "Hiranandani Estate Thane Bldg Name: Bayer House - 10K Sq Feet",
    area: "Thane",
    location: "Mumbai",
    year: "2014",
    client: "M/S Sew Engg",
    contactPerson: "Mr. Nandakumar Pawar",
    contactNumber: "8828092974",
    amount: "₹ 400,000.00",
  },
  {
    srNo: 8,
    project: "Hiranandani Estate Thane: Walk Shopping Center - 15K Sq Feet",
    area: "Thane",
    location: "Mumbai",
    year: "2016-17",
    client: "M/S Reflexions Pvt Ltd",
    contactPerson: "Mr. Zubair Sidquee",
    contactNumber: "9004348047",
    amount: "₹ 600,000.00",
  },
  {
    srNo: 9,
    project: "Hiranandani Garden Pawai Bldg Name: EVA - 23 Floors, 182 Flats",
    area: "Thane",
    location: "Mumbai",
    year: "Ongoing",
    client: "M/S Sew Engg",
    contactPerson: "Mr. Rahul Gosavi",
    contactNumber: "7718827809",
    amount: "₹ 5,900,000.00",
  },
  {
    srNo: 10,
    project: "Rustomjee Arbania Wing (Labour) - 32 Floors, 124 Flats",
    area: "Thane",
    location: "Mumbai",
    year: "2016-18",
    client: "M/S Sew Engg",
    contactPerson: "Mr. Rahul Gosavi",
    contactNumber: "7718827809",
    amount: "₹ 5,100,000.00",
  },
  {
    srNo: 11,
    project:
      "RESTAURANT AT: BURGER KING, BOTTONS UP, THEOBROMA, CHAI POINT, STREET FOOD BY PUNJAB",
    area: "9K SQ FEET",
    location: "Mumbai International Airport Terminal 2",
    year: "2015-16",
    client: "M/S LITE BITE",
    contactPerson: "Mr. Shrawan",
    contactNumber: "9022074747",
    amount: "₹ 900,000.00",
  },
  {
    srNo: 12,
    project: "CHAI POINT AT HINJEWADI, CHAI POINT AT MAGARPATTA",
    area: "300 SQ FEET",
    location: "Pune",
    year: "2015-2016",
    client: "M/S KSHAMATA PROJECTS",
    contactPerson: "Mr. Virendra Shiv",
    contactNumber: "7718871817",
    amount: "₹ 600,000.00",
  },
  {
    srNo: 13,
    project: "CHEP INDIA",
    area: "8K SQ FEET",
    location: "Andheri",
    year: "2016",
    client: "M/S REFLEXIONS PVT LTD",
    contactPerson: "Mr. Zubair Sidquee",
    contactNumber: "9004348047",
    amount: "₹ 300,000.00",
  },
  {
    srNo: 14,
    project: "BHUMIPUTRA BHAVAN AUDITORIUM CIDCO (LABOUR JOB)",
    area: "8 FLOORS",
    location: "Ulwe",
    year: "2018-20",
    client: "M/S LEENA POWER TECH",
    contactPerson: "Mr. Abhishek Patil",
    contactNumber: "9833297409",
    amount: "₹ 2,800,000.00",
  },
  {
    srNo: 15,
    project: "AT ICC TOWER 1 & 2 DADAR",
    area: "10K SQ FEET",
    location: "Dadar (East)",
    year: "2018-19",
    client: "M/S KOOL KRAFT ENGG",
    contactPerson: "Mr. Anmol Kohli",
    contactNumber: "9833166847",
    amount: "₹ 2,500,000.00",
  },
  {
    srNo: 16,
    project: "NEW DISTRICT HEADQUARTER CIDCO",
    area: "30K",
    location: "Palghar",
    year: "2020-21",
    client: "M/S LEENA POWER TECH",
    contactPerson: "Mr. Mahendra Kanthe",
    contactNumber: "9867030705",
    amount: "₹ 2,500,000.00",
  },
  {
    srNo: 17,
    project: "RESTAURANTS: HRC, SIERO",
    area: "6K SQ FEET",
    location: "NESCO Goregaon",
    year: "Ongoing",
    client: "M/S GRADE ELECTRICAL",
    contactPerson: "Mr. Chandrakant Tripathi",
    contactNumber: "7506684148",
    amount: "₹ 450,000.00",
  },
  {
    srNo: 18,
    project: "HIRANANDANI PAWAI: REGENT HILL (LABOUR JOB)",
    area: "1.2K SQ FT",
    location: "Powai",
    year: "2020-22",
    client: "M/S SEW ENGG",
    contactPerson: "Mr. Rahul Gosavi",
    contactNumber: "7718827809",
    amount: "₹ 5,900,000.00",
  },
  {
    srNo: 20,
    project:
      "SARASWATI INTERNATIONAL SCHOOL - JOINT VENTURE WITH M/S MICRO POWERTECH",
    area: "84K SQ FT",
    location: "Airoli",
    year: "2022-23",
    client: "M/S SIDUS BUILDCON",
    contactPerson: "Mr. Nandkumar Pawar",
    contactNumber: "8828092974",
    amount: "₹ 11,200,000.00",
  },
  {
    srNo: 21,
    project:
      "SKILL DEVELOPMENT CENTER - JOINT VENTURE WITH M/S MICRO POWERTECH",
    area: "18K SQ FT",
    location: "Ratnagiri",
    year: "2022-23",
    client: "M/S SIDUS BUILDCON",
    contactPerson: "Mr. Nandkumar Pawar",
    contactNumber: "8828092974",
    amount: "₹ 3,200,000.00",
  },
  {
    srNo: 22,
    project: "BUNGALOW (APAR INDU) - JOINT VENTURE WITH M/S MICRO POWERTECH",
    area: "8 ACRES",
    location: "Lonavala",
    year: "Ongoing",
    client: "M/S APAR INDUSTRIES",
    contactPerson: "Mr. Sachin Lippare",
    contactNumber: "7710042914",
    amount: "₹ 19,000,000.00",
  },
  {
    srNo: 24,
    project: "CET EXAMINATION CENTERS - JOINT VENTURE WITH M/S MICRO POWERTECH",
    area: "1.1L SQ FT, 1800 SITTINGS",
    location: "Five districts in Maharashtra",
    year: "2023-25",
    client: "M/S ALATARA PRO",
    contactPerson: "Mr. Mehroosh Raanderia",
    contactNumber: "7506063648",
    amount: "₹ 9,500,000.00",
  },
  {
    srNo: 25,
    project:
      "SKILL DEVELOPMENT CENTER - JOINT VENTURE WITH M/S MICRO POWERTECH",
    area: "42 K SQ FT",
    location: "NASHIK, RANJANGAON PUNE",
    year: "24-25",
    client: "M/S ALATARA PRO",
    contactPerson: "MR MEHROOSH RAANDERIA",
    contactNumber: "7506063648",
    amount: "₹ 8,500,000.00",
  },
  {
    srNo: 26,
    project: "NAVI MUMBAI AIRPORT (LABOUR JOB)",
    area: "40 K SQ FT",
    location: "NAVI MUMBAI",
    year: "24-25",
    client: "ANTELEC PVT - KINDEN GROUP OF COMPANIES",
    contactPerson: "MR SATISH BHOSALE",
    contactNumber: "9029066187",
    amount: "₹ 6,300,000.00",
  },
  {
    srNo: 27,
    project: "N K DESAI HOSPITAL (LABOUR JOB)",
    area: "78 K SQ FT",
    location: "GULBARGA, KARNATAK",
    year: "24-25",
    client: "M/S SEW ENGG",
    contactPerson: "MR SANJEEV KADEPURE",
    contactNumber: "9867030729",
    amount: "₹ 5,300,000.00",
  },
  {
    srNo: 28,
    project:
      "J POD AT HYDERABAD AIRPORT - JOINT VENTURE WITH M/S MICRO POWERTECH",
    area: "9 K SQ FT",
    location: "HYDERABAD",
    year: "23-24",
    client: "M/S PAWANPUTRAA ENGG",
    contactPerson: "MR DHARAM MASTER",
    contactNumber: "9664155548",
    amount: "₹ 3,200,000.00",
  },
  {
    srNo: 29,
    project: "AMPLIFONE OUTLETS AT HYDERABAD",
    area: "2 K SQ FT",
    location: "HYDERABAD",
    year: "22-23",
    client: "M/S MANVIN ENT",
    contactPerson: "MR VIRENDRA SING",
    contactNumber: "",
    amount: "₹ 2,200,000.00",
  },
  {
    srNo: 30,
    project:
      "PRAMOD MAHAJAN SPORTS COMPLEX BORIVALI - JOINT VENTURE WITH M/S MICRO POWERTECH",
    area: "9 ACRES",
    location: "BORIVALI, MUMBAI",
    year: "24-25",
    client: "M/S SIDUS BUILDCON",
    contactPerson: "MR NANDKUMAR PAWAR",
    contactNumber: "8828092974",
    amount: "₹ 11,200,000.00",
  },
  {
    srNo: 31,
    project:
      "RUSTOMJEE PARAMOUNT 23 FL RESIDENTIAL BLDG - JOINT VENTURE WITH M/S MICRO POWERTECH",
    area: "45 K SQ FT",
    location: "KHAR, MUMBAI",
    year: "ONGOING",
    client: "RUSTOMJEE DEVELOPER",
    contactPerson: "MR MAHESH GHAG",
    contactNumber: "",
    amount: "₹ 21,200,000.00",
  },
  {
    srNo: 32,
    project: "JSW STAFF TOWNSHIP - 91 FLATS",
    area: "PEN, DOLVI",
    location: "PEN, MAHARATRA",
    year: "ONGOING",
    client: "M/S JSW",
    contactPerson: "MR KETAN MHATRE",
    contactNumber: "",
    amount: "₹ 110,000,000.00",
  },
  {
    srNo: 33,
    project: "JSW STAFF TOWNSHIP - 48 STUDIO APT",
    area: "PEN, DOLVI",
    location: "PEN, MAHARATRA",
    year: "ONGOING",
    client: "M/S JSW",
    contactPerson: "MR KETAN MHATRE",
    contactNumber: "",
    amount: "₹ 7,800,000.00",
  },
  {
    srNo: 34,
    project: "VEBVGYORE SCHOOL",
    area: "1.1 L SQ FT",
    location: "BELAPUR",
    year: "ONGOING",
    client: "M/S ALATARA PRO",
    contactPerson: "MR MEHROOSH RAANDERIA",
    contactNumber: "7506063648",
    amount: "₹ 12,400,000.00",
  },
  {
    srNo: 35,
    project: "SUB STATION AT VIBGYORE SCHOOL",
    area: "800 SQ FT",
    location: "BELAPUR",
    year: "24-25",
    client: "M/S ALATARA PRO",
    contactPerson: "MR MEHROOSH RAANDERIA",
    contactNumber: "7506063648",
    amount: "₹ 7,600,000.00",
  },
  {
    srNo: 36,
    project: "NCRD SCHOOL",
    area: "76 K SQ FT",
    location: "NERUL",
    year: "ONGOING",
    client: "M/S SIDUS BUILDCON",
    contactPerson: "MR NANDKUMAR PAWAR",
    contactNumber: "8828092974",
    amount: "₹ 9,600,000.00",
  },
  {
    srNo: 37,
    project: "Fr AGNEL SCHOOL",
    area: "70 K SQ FT",
    location: "VADHVA CITY, PANVEL",
    year: "ONGOING",
    client: "M/S SIDUS BUILDCON",
    contactPerson: "MR NANDKUMAR PAWAR",
    contactNumber: "8828092974",
    amount: "₹ 17,000,000.00",
  },
  {
    srNo: 38,
    project: "RAPTOKAS CORPORATE OFFICE (LABOUR JOB)",
    area: "1.6 L SQ FT",
    location: "VORLI, MUMBAI",
    year: "ONGOING",
    client: "M/S SEW ENGG",
    contactPerson: "MR SANJEEV KADEPURE",
    contactNumber: "9867030729",
    amount: "₹ 1,60,000.00",
  },
];

const servicesData = [
  {
    title: "High/Low Voltage Infrastructure Development",
    description:
      "Expert installation and management of high and low voltage systems, ensuring reliability and efficiency for all your infrastructure needs.",
  },
  {
    title: "Power Upgradation",
    description:
      "Comprehensive power upgradation services to meet the increasing energy demands of modern facilities and infrastructure.",
  },
  {
    title: "Lighting and Power Distribution",
    description:
      "Tailored solutions for efficient and effective lighting and power distribution, ensuring optimal energy use and safety.",
  },
  {
    title: "Integrated Solutions for Network and Security",
    description:
      "We offer integrated solutions that combine computer networks, data, voice, fire access, surveillance, and security systems.",
  },
  {
    title: "Fire Safety and Access Control",
    description:
      "State-of-the-art fire safety and access control systems to ensure the security and safety of your premises.",
  },
  {
    title: "Surveillance and Security Systems",
    description:
      "Advanced surveillance and security systems designed to protect your assets and ensure peace of mind.",
  },
];

export {
  servicesData,
  msAppartment,
  hydAirport,
  hirandaini,
  naviAirport,
  desai,
  PROJECTS,
};
